using System.ComponentModel.DataAnnotations;

namespace DeliveryManagementAPI.Models
{
    /// <summary>
    /// DTO để nhận dữ liệu khi tạo đơn hàng mới
    /// Bao gồm validation cho tất cả các trường
    /// </summary>
    public class CreateOrderDto
    {
        /// <summary>
        /// Mã đơn hàng (auto-generated by system)
        /// Format: DH + yyyyMMddHHmmss + random 3 digits
        /// Example: DH20260406104530987
        /// Generated on server side, client can leave empty
        /// </summary>
        [MaxLength(50, ErrorMessage = "Mã đơn hàng không được vượt quá 50 ký tự")]
        public string? OrderCode { get; set; }
        
        // ========== THÔNG TIN KHÁCH HÀNG ==========
        
        /// <summary>
        /// Tên khách hàng
        /// </summary>
        [Required(ErrorMessage = "Tên khách hàng không được để trống")]
        public string CustomerName { get; set; } = string.Empty;

        /// <summary>
        /// Số điện thoại khách hàng
        /// </summary>
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        public string CustomerPhone { get; set; } = string.Empty;

        /// <summary>
        /// Địa chỉ giao hàng
        /// </summary>
        [Required(ErrorMessage = "Địa chỉ giao hàng không được để trống")]
        public string DeliveryAddress { get; set; } = string.Empty;

        /// <summary>
        /// Phường/Xã
        /// </summary>
        [Required(ErrorMessage = "Phường/Xã không được để trống")]
        public string Ward { get; set; } = string.Empty;

        /// <summary>
        /// Quận/Huyện
        /// </summary>
        [Required(ErrorMessage = "Quận/Huyện không được để trống")]
        public string District { get; set; } = string.Empty;

        /// <summary>
        /// Thành Phố
        /// </summary>
        [Required(ErrorMessage = "Thành Phố không được để trống")]
        public string City { get; set; } = string.Empty;
        
        // ========== THÔNG TIN HÀNG HÓA ==========
        
        /// <summary>
        /// ID Sản phẩm (ProductId từ Products table)
        /// Optional - nếu không chọn, backend sẽ set default = 1
        /// </summary>
        [Range(0, int.MaxValue, ErrorMessage = "ID sản phẩm không hợp lệ")]
        public int ProductId { get; set; } = 1;

        /// <summary>
        /// Loại hàng
        /// Options: "Gói nhỏ", "Gói lớn", "Gói chuẩn", "Khác"
        /// </summary>
        public PackageType PackageType { get; set; }

        /// <summary>
        /// Trọng lượng (kg)
        /// <summary>
        /// Trọng lượng (kg)
        /// </summary>
        [Required(ErrorMessage = "Trọng lượng không được để trống")]
        public double Weight { get; set; }

        /// <summary>
        /// Kích thước (LxWxH cm) - stored as string e.g., "10x10x10"
        /// </summary>
        [Required(ErrorMessage = "Kích thước không được để trống")]
        public string Size { get; set; } = string.Empty;

        /// <summary>
        /// Khoảng cách (km)
        /// </summary>
        [Required(ErrorMessage = "Khoảng cách không được để trống")]
        public double Distance { get; set; }
        
        // ========== THÔNG SỐ ĐẶC BIỆT ==========
        
        /// <summary>
        /// Hàng dễ vỡ
        /// </summary>
        public bool IsFragile { get; set; } = false;

        /// <summary>
        /// Hàng trị giá cao
        /// </summary>
        public bool IsValuable { get; set; } = false;

        /// <summary>
        /// Hàng cồng kềnh (xe, v.v.)
        /// </summary>
        public bool IsVehicle { get; set; } = false;

        /// <summary>
        /// Thu tiền hộ (COD)
        /// </summary>
        public bool CollectMoney { get; set; } = false;

        /// <summary>
        /// Số tiền COD (nếu chọn)
        /// </summary>
        public decimal CollectionAmount { get; set; } = 0;
        
        // ========== THANH TOÁN ==========
        
        /// <summary>
        /// Phương thức thanh toán
        /// Options: 0=COD, 1=Online
        /// </summary>
        [Required(ErrorMessage = "Phương thức thanh toán phải được chọn")]
        public PaymentMethod PaymentMethod { get; set; } = PaymentMethod.COD;

        /// <summary>
        /// Loại giao hàng
        /// Options: 0=Thường, 1=Nhanh
        /// </summary>
        [Required(ErrorMessage = "Loại giao hàng phải được chọn")]
        public DeliveryType DeliveryType { get; set; } = DeliveryType.GiaoHangThuong;
        
        /// <summary>
        /// Cổng thanh toán (Momo, VNPay, etc.) - Chỉ dùng khi PaymentMethod = Online
        /// </summary>
        public string? PaymentGateway { get; set; }
        
        /// <summary>
        /// Ghi chú
        /// Optional, max 500 ký tự
        /// </summary>
        [MaxLength(500, ErrorMessage = "Ghi chú không được vượt quá 500 ký tự")]
        public string Notes { get; set; } = string.Empty;
    }

    /// <summary>
    /// DTO trả về sau khi tạo đơn hàng thành công
    /// </summary>
    public class CreateOrderResponseDto
    {
        public int OrderId { get; set; }
        public string OrderCode { get; set; } = string.Empty;
        public string CustomerName { get; set; } = string.Empty;
        public string DeliveryAddress { get; set; } = string.Empty;
        public decimal ShippingFee { get; set; }
        public decimal? CODAmount { get; set; }
        public string PaymentMethod { get; set; } = string.Empty;
        public string DeliveryType { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public DateTime CreatedDate { get; set; }
        public string Message { get; set; } = "Tạo đơn hàng thành công";
    }
}
